from fastapi import APIRouter, Depends, HTTPException
from fastapi.responses import StreamingResponse
from sqlmodel import Session, select
import json
import time
from datetime import date
from pydantic import BaseModel

from app.core.db import get_session
from app.models.blog import Blog
from app.services.agent import graph

# APIRouter is used to group related API endpoints together for scalability.
# We will include this router in the main FastAPI app with a prefix.
router = APIRouter()

class BlogGenerateRequest(BaseModel):
    topic: str
    tone: str
    audience: str
    model_name: str
    length: str = "Medium (~1000 words)"

@router.post("/generate")
def generate_blog(payload: BlogGenerateRequest, session: Session = Depends(get_session)):
    """
    Core entry point. Creates a database record with PENDING status
    and returns the blog_id immediately.
    """
    db_blog = Blog(
        topic=payload.topic,
        tone=payload.tone,
        audience=payload.audience,
        model_name=payload.model_name,
        length=payload.length,
        mode="auto",
        status="PENDING"
    )
    session.add(db_blog)
    session.commit()
    # Refresh retrieves the autogenerated ID from Postgres
    session.refresh(db_blog)
    
    return {"blog_id": db_blog.id}

@router.get("/stream/{blog_id}")
def stream_blog(blog_id: int, session: Session = Depends(get_session)):
    """
    Server-Sent Events (SSE) streaming endpoint.
    It triggers the LangGraph workflow and yields live updates back to the frontend.
    """
    db_blog = session.get(Blog, blog_id)
    if not db_blog:
        raise HTTPException(status_code=404, detail="Blog not found")

    def event_generator():
        # Update database status to GENERATING
        start_time = time.time()
        db_blog.status = "GENERATING"
        session.add(db_blog)
        session.commit()
        session.refresh(db_blog)

        current_logs = ["Sending request to start agent workflow...", f"Created blog record #{db_blog.id}. Opening SSE stream..."]
        current_plan = {}
        current_evidence = []

        try:
            # Inputs to populate the LangGraph state
            inputs = {
                "topic": db_blog.topic,
                "mode": "auto",  # The router will overwrite this
                "model_name": db_blog.model_name or "GPT-4o",
                "length": db_blog.length or "Medium (~1000 words)",
                "need_research": False,
                "queries": [],
                "evidence": [],
                "plan": None,
                "as_of": date.today().isoformat(),
                "recency_days": 7,
                "sections": [],
                "merged_md": "",
                "md_with_placeholders": "",
                "image_specs": [],
                "final_blog": "",
                "metrics": [],
            }

            final_state = None
            current_metrics = []
            
            # Iterate through the graph nodes as they run
            for event in graph.stream(inputs):
                final_state = event  # Keep track of the latest node output
                
                # event is a dictionary like: {'node_name': {state_updates}}
                node_name = list(event.keys())[0]
                
                # Map the executing node to a clean user-facing status message
                status_map = {
                    "router": {"status": "routing", "message": "Analyzing topic and determining workflow..."},
                    "research": {"status": "researching", "message": "Scouring the web for latest technical evidence..."},
                    "orchestrator": {"status": "orchestrating", "message": "Orchestrating blog structure and detailed outline..."},
                    "worker": {"status": "writing", "message": "Drafting blog sections concurrently..."},
                    "reducer": {"status": "finalizing", "message": "Assembling sections and generating images..."}
                }
                
                info = status_map.get(node_name, {"status": "generating", "message": f"Processing {node_name}..."})
                current_logs.append(f"[{info['status'].upper()}] {info['message']}")
                
                # Check if we have specific data to push to frontend tabs
                if node_name == "router" and "mode" in event[node_name]:
                    info["mode"] = event[node_name]["mode"]
                    db_blog.mode = event[node_name]["mode"] # Save AI decision to DB
                    session.add(db_blog)
                    session.commit()
                if node_name == "research" and "evidence" in event[node_name]:
                    evidence = event[node_name]["evidence"]
                    current_evidence = [e.model_dump() if hasattr(e, 'model_dump') else dict(e) for e in evidence]
                    info["evidence"] = current_evidence
                if node_name == "orchestrator" and "plan" in event[node_name]:
                    plan = event[node_name]["plan"]
                    current_plan = plan.model_dump() if hasattr(plan, 'model_dump') else dict(plan)
                    info["plan"] = current_plan
                    
                if "metrics" in event[node_name] and event[node_name]["metrics"]:
                    current_metrics.extend(event[node_name]["metrics"])
                    info["metrics"] = current_metrics
                
                info["latency"] = round(time.time() - start_time, 2)
                
                # SSE format requires starting with "data: " and ending with double newlines "\n\n"
                yield f"data: {json.dumps(info)}\n\n"

            # Retrieve final blog output from the reducer subgraph node output
            final_blog = None
            if final_state and "reducer" in final_state:
                final_blog = final_state["reducer"].get("final_blog")
            
            # Safe fallback lookup if the dict structure is nested differently
            if not final_blog and final_state:
                for val in final_state.values():
                    if isinstance(val, dict) and "final_blog" in val:
                        final_blog = val["final_blog"]
                        break

            if final_blog:
                # Save the final Markdown back to our PostgreSQL database
                db_blog.markdown_content = final_blog
                db_blog.status = "COMPLETED"
                db_blog.plan = current_plan
                db_blog.evidence = current_evidence
                db_blog.metrics = current_metrics
                current_logs.append("[COMPLETE] Blog generated successfully!")
                db_blog.logs = current_logs
                session.add(db_blog)
                session.commit()
                
                yield f"data: {json.dumps({'status': 'complete', 'message': 'Blog generated successfully!'})}\n\n"
            else:
                raise ValueError("Graph execution finished but failed to generate blog markdown.")

        except Exception as e:
            # If anything fails, save the status as ERROR
            db_blog.status = "ERROR"
            session.add(db_blog)
            session.commit()
            
            error_info = {"status": "error", "message": f"Workflow failed: {str(e)}"}
            yield f"data: {json.dumps(error_info)}\n\n"

    # text/event-stream content type triggers EventSource SSE handling in browsers
    return StreamingResponse(event_generator(), media_type="text/event-stream")

@router.get("/")
def list_blogs(session: Session = Depends(get_session)):
    """
    List all historically generated blogs from the database.
    """
    statement = select(Blog).where(Blog.status == "COMPLETED").order_by(Blog.created_at.desc())
    results = session.exec(statement).all()
    return results

@router.get("/{blog_id}")
def get_blog(blog_id: int, session: Session = Depends(get_session)):
    """
    Retrieve details and markdown content of a specific blog by ID.
    """
    db_blog = session.get(Blog, blog_id)
    if not db_blog:
        raise HTTPException(status_code=404, detail="Blog not found")
    return db_blog
