from typing import TypedDict, Annotated, List, Literal, Optional
import operator
from pydantic import BaseModel, Field

# ------------------------------------------------------------
# Pydantic Schemas for LangGraph State and structured output
# ------------------------------------------------------------

class Task(BaseModel):
    """
    Schema representing a single section writing task within the outline.
    """
    id: int
    title: str
    goal: str = Field(
        ...,
        description="One sentence describing what the reader should be able to do /understand after this section."
    )
    bullets: List[str] = Field(
        ...,
        min_length=3,
        max_length=5,
        description="3-5 concrete non-overlapping subpoints to cover in this section"
    )
    target_words: int = Field(
        ...,
        description="target word count for this section is (120-450)"
    )
    tags: List[str] = Field(default_factory=list)
    requires_research: bool = False
    requires_citations: bool = False
    requires_code: bool = False


class Plan(BaseModel):
    """
    Schema representing the global plan / outline generated by the Orchestrator.
    """
    blog_title: str
    audience: str = Field(
        ...,
        description="who this blog is for."
    )
    tone: str = Field(
        ...,
        description="Writing tone of this blog (e.g., practical, crisp)."
    )
    blog_kind: Literal[
        "explainer",
        "tutorial",
        "news_roundup",
        "comparison",
        "system_design",
        "listicle",
        "lifestyle",
        "opinion",
        "review",
        "general"
    ] = "general"
    constraints: List[str] = Field(default_factory=list)
    tasks: List[Task]


class EvidenceItem(BaseModel):
    """
    Schema representing a snippet of real-world research evidence.
    """
    title: str
    url: str
    published_at: Optional[str] = None
    snippet: Optional[str] = None
    source: Optional[str] = None


class EvidencePack(BaseModel):
    """
    Schema representing a collection of researched evidence.
    """
    evidence: List[EvidenceItem] = Field(default_factory=list)


class RouterDecision(BaseModel):
    """
    Structured output for the Router agent.
    """
    need_research: bool
    mode: Literal["closed_book", "hybrid", "open_book"]
    queries: List[str] = Field(default_factory=list)


class ImageSpec(BaseModel):
    """
    Structured output specifying how DALL-E-3 should render a blog image.
    """
    task_id: int = Field(..., description="The ID of the task/section where this image should be inserted.")
    filename: str = Field(..., description="Save under /images, e.g. abc_flow.png")
    alt: str
    caption: str
    prompt: str = Field(..., description="Prompt to send to image model")
    size: Literal["1536x1024"] = "1536x1024"
    quality: Literal["low", "medium"] = "medium"
    placeholder: Optional[str] = None # Filled programmatically


class GlobalImagePlan(BaseModel):
    """
    Collection of planned images for the blog post.
    """
    images: List[ImageSpec] = Field(default_factory=list)


class BlogState(TypedDict):
    """
    TypedDict representing the shared graph state updated by active nodes.
    """
    topic: str
    model_name: str
    depth: str
    reference_urls: Optional[str]
    
    # Routing and Research
    mode: str
    need_research: bool
    queries: List[str]
    evidence: List[EvidenceItem]
    plan: Optional[Plan]

    # Recency Control
    as_of: str           # ISO date, e.g. "2026-01-29"
    recency_days: int    # Date range scope for Tavily Search

    # Workers output channel
    sections: Annotated[List[tuple[int, str]], operator.add]

    # Content assembly & images
    merged_md: str
    md_with_placeholders: str
    image_specs: List[dict]

    # Final completed output
    final_blog: str
    seo_metadata: dict
    
    # Accumulator of token usage metrics across nodes
    metrics: Annotated[List[dict], operator.add]
    
    # User custom credentials
    cloudinary_cloud_name: Optional[str]
    cloudinary_api_key: Optional[str]
    cloudinary_api_secret: Optional[str]
    brand_persona: Optional[str]
    plan_name: Optional[str]


class SEOMetadata(BaseModel):
    """
    Structured schema representing blog SEO details.
    """
    meta_description: str
    slug: str
    focus_keywords: List[str]


class EditorOutput(BaseModel):
    """
    Structured output schema for the Editor Node.
    """
    seo_metadata: SEOMetadata
    youtube_embed_html: Optional[str] = Field(default=None, description="If highly relevant, an HTML iframe tag for a YouTube video. Provide ONLY the iframe tag.")


def fetch_youtube_video(topic: str) -> str:
    """
    Crawl YouTube API for the most relevant video tutorial explaining the blog topic
    and returns a clean embeddable iframe tag.
    """
    try:
        from googleapiclient.discovery import build
    except ImportError:
        return ""
        
    api_key = settings.YOUTUBE_API_KEY or os.getenv("YOUTUBE_API_KEY")
    if not api_key:
        print("YOUTUBE_API_KEY not found in .env, skipping YouTube integration.")
        return ""
    
    youtube = build("youtube", "v3", developerKey=api_key)
    query = f"{topic} tutorial explanation"
    
    try:
        request = youtube.search().list(
            part="snippet",
            q=query,
            type="video",
            maxResults=1,
            order="relevance",
            videoEmbeddable="true"
        )
        response = request.execute()
        
        if "items" in response and len(response["items"]) > 0:
            video_id = response["items"][0]["id"]["videoId"]
            title = response["items"][0]["snippet"]["title"]
            
            iframe = (
                f'\n\n## Related Video Tutorial\n\n'
                f'<p align="center">\n'
                f'  <iframe width="750" height="422" src="https://www.youtube.com/embed/{video_id}" '
                f'frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" '
                f'allowfullscreen style="max-width: 100%; border-radius: 8px; box-shadow: 0 10px 15px -3px rgb(0 0 0 / 0.1);"></iframe>\n'
                f'  <br />\n'
                f'  <em>{title}</em>\n'
                f'</p>\n'
            )
            return iframe
        return ""
    except Exception as e:
        print(f"YouTube search error: {e}")
        return ""


