"""add image_model_name

Revision ID: 65dd24d72aa2
Revises: c51ccd5e7505
Create Date: 2026-07-20 10:32:36.892539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '65dd24d72aa2'
down_revision: Union[str, Sequence[str], None] = 'c51ccd5e7505'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog', sa.Column('image_model_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog', 'image_model_name')
    # ### end Alembic commands ###
