"""Add CMS and brand persona fields

Revision ID: 84ebcc6ef7a9
Revises: 9d777d417164
Create Date: 2026-07-17 20:14:39.911034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '84ebcc6ef7a9'
down_revision: Union[str, Sequence[str], None] = '9d777d417164'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog', sa.Column('published_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('blog', sa.Column('cms_platform', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('brand_persona', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('cms_wordpress_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('cms_wordpress_username', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('cms_wordpress_app_password', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('cms_medium_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'cms_medium_token')
    op.drop_column('user', 'cms_wordpress_app_password')
    op.drop_column('user', 'cms_wordpress_username')
    op.drop_column('user', 'cms_wordpress_url')
    op.drop_column('user', 'brand_persona')
    op.drop_column('blog', 'cms_platform')
    op.drop_column('blog', 'published_url')
    # ### end Alembic commands ###
