"""Add payment transaction and plan_expires_at

Revision ID: 9d777d417164
Revises: beea4b56c231
Create Date: 2026-07-17 17:51:08.426276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9d777d417164'
down_revision: Union[str, Sequence[str], None] = 'beea4b56c231'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paymenttransaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('razorpay_order_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('razorpay_payment_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paymenttransaction_razorpay_order_id'), 'paymenttransaction', ['razorpay_order_id'], unique=False)
    op.create_index(op.f('ix_paymenttransaction_razorpay_payment_id'), 'paymenttransaction', ['razorpay_payment_id'], unique=False)
    op.create_index(op.f('ix_paymenttransaction_user_id'), 'paymenttransaction', ['user_id'], unique=False)
    op.add_column('user', sa.Column('plan_expires_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'plan_expires_at')
    op.drop_index(op.f('ix_paymenttransaction_user_id'), table_name='paymenttransaction')
    op.drop_index(op.f('ix_paymenttransaction_razorpay_payment_id'), table_name='paymenttransaction')
    op.drop_index(op.f('ix_paymenttransaction_razorpay_order_id'), table_name='paymenttransaction')
    op.drop_table('paymenttransaction')
    # ### end Alembic commands ###
