"""Add cloudinary fields

Revision ID: beea4b56c231
Revises: 
Create Date: 2026-07-17 15:52:21.125068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'beea4b56c231'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('blog', 'latency',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0.0'))
    op.alter_column('blog', 'mode',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('user', sa.Column('cloudinary_cloud_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('cloudinary_api_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('cloudinary_api_secret', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('user', 'plan_name',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'Free'::character varying"))
    op.alter_column('user', 'credits',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('5'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'credits',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('5'))
    op.alter_column('user', 'plan_name',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'Free'::character varying"))
    op.drop_column('user', 'cloudinary_api_secret')
    op.drop_column('user', 'cloudinary_api_key')
    op.drop_column('user', 'cloudinary_cloud_name')
    op.alter_column('blog', 'mode',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('blog', 'latency',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0.0'))
    # ### end Alembic commands ###
