"""Added OTP verification to users

Revision ID: c51ccd5e7505
Revises: c690cd506edc
Create Date: 2026-07-19 11:40:41.362704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c51ccd5e7505'
down_revision: Union[str, Sequence[str], None] = 'c690cd506edc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_verified', sa.Boolean(), nullable=False, server_default='0'))
    op.add_column('user', sa.Column('otp_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('otp_expires_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'otp_expires_at')
    op.drop_column('user', 'otp_code')
    op.drop_column('user', 'is_verified')
    # ### end Alembic commands ###
