"""add linkedin cms fields

Revision ID: c690cd506edc
Revises: 84ebcc6ef7a9
Create Date: 2026-07-17 22:08:45.522800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c690cd506edc'
down_revision: Union[str, Sequence[str], None] = '84ebcc6ef7a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('cms_linkedin_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('user', sa.Column('cms_linkedin_author_urn', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'cms_linkedin_author_urn')
    op.drop_column('user', 'cms_linkedin_token')
    # ### end Alembic commands ###
